### ISSUE TITLE
Install Vagrant generates this message "The machine with the name 'web' was not found configured for this Vagrant environment."

### ISSUE THREAD

**Issue by Abdelkrim** [bigdatabe/p2#4]
I am following the installation guide on this page: https://github.com/bigdatabe/p2/tree/master/vagrant
1. I have downloaded Vagrant
2. I have installed it
3. I executed the command: git submodule update --init
4. I executed the command: vagrant up web

But, this message appeared "A Vagrant environment is required to run this command. Run `vagrant init` to set one up in this directory, or change to a directory with a Vagrantfile and try again."
1. I executed : vagrant init
2. I executed: vagrant up web

But, this message appeared "The machine with the name 'web' was not found configured for this Vagrant environment."

What should I do now?

thanks in advance for your help

**Comment by kennyhelsens** [comment]
This must be some refactoring issue, the web was apparently renamed into worker.

Try this:
vagrant up worker

**Comment by Abdelkrim** [comment]
Sorry but "vagrant up worker" doesn't work neither.

PS: in the meantime I will download the image from dropbox.

# WHAT STEPS WILL REPRODUCE THE PROBLEM?
1. I am located on this directory: ''p2''
2. I create the VagrantFile using ''vagrant init''
3. I run the command ''vagrant up worker''

# OUTPUT

"The machine with the name 'worker' was not found configured for this Vagrant environment."

**Comment by kennyhelsens** [comment]
Just to be sure, did you execute the command in the same folder as the Vagrantfile?
—
Kenny Helsens - mobile

**Comment by Abdelkrim** [comment]
yes, I have executed the command in the same folder as the Vagrantfile

**Comment by kennyhelsens** [comment]
hmm, it works fine here. We'll fix it tonight. Thanks for testing!
—
Kenny Helsens - mobile

**Comment by Abdelkrim** [comment]
@kennyhelsens I inivte you to start with a git clone (from scratch)

then you might be able to reproduce the issue ?

see you tonight

**Comment by Abdelkrim** [comment]
Case is closed, the vagrantfile wasn't at the root of the repository :-)

now it works, I have changed the documentation accordingly
